import './globals.css'
import NavigationBar from "@/client/NavigatioBar"
import Footer from "../components/Footer"



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "#FFFCFC"}}>
        <header>
          <nav>
            <NavigationBar/>
          </nav>
        </header>
        <main className='main'>
          {children}
        </main>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  )
}
